refactor(wip): stout-rummy

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,22 +6,28 @@ on:
     tags:
       - v*
   workflow_dispatch:
-
+defaults:
+  run:
+    shell: bash
+    working-directory: .
 jobs:
   test:
     runs-on: ubuntu-latest
     timeout-minutes: 10
     steps:
-      - name: aqua-install
-        run: |
-          curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v1.1.2/aqua-installer | bash -s -- -i /usr/local/bin/aqua
-          echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> $GITHUB_PATH
-          [[ -e "${AQUA_CONFIG}" ]] && echo "✅ AQUA_CONFIG: ${AQUA_CONFIG} exists" ||  echo "::error ❗ unable to validate the target file: ${AQUA_CONFIG} exists"
-          aqua install # --only-link
-        env:
-          AQUA_CONFIG: aqua.ci.yaml
-          AQUA_LOG_LEVEL: debug
-          AQUA_OPTS: ""
+      - uses: aquaproj/aqua-installer@v1.1.2
+        with:
+          aqua_version: v1.20.2
+          enable_aqua_install: true
+      # - name: aqua-install
+      #   run: |
+      #     curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v1.1.2/aqua-installer | bash -s -- -i /usr/local/bin/aqua
+      #     echo "$HOME/.local/share/aquaproj-aqua/bin" >> $GITHUB_PATH
+      #     # [[ -e "${AQUA_CONFIG}" ]] && echo "✅ AQUA_CONFIG: ${AQUA_CONFIG} exists" ||  echo "::error ❗ unable to validate the target file: ${AQUA_CONFIG} exists"
+      #   env:
+      #     # AQUA_CONFIG: aqua.yaml
+      #     AQUA_LOG_LEVEL: debug
+      #     AQUA_OPTS: ""
       - name: env-config-go
         run: |
           echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
@@ -37,12 +43,13 @@ jobs:
 
       - name: mage-init
         run: |
-          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:${PATH}"
+          # export PATH="${HOME}/.local/share/aquaproj-aqua/bin:${PATH}"
           export PATH="$(go env GOPATH)/bin:${PATH}"
+          # aqua install # --only-link
           mage init
       - name: mage-testsum
         run: |
-          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:${PATH}"
+          # export PATH="$HOME/.local/share/aquaproj-aqua/bin:${PATH}"
           export PATH="$(go env GOPATH)/bin:${PATH}"
           mage go:testsum ./...
         env:
