ci: get github release working

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -16,23 +16,27 @@ jobs:
     timeout-minutes: 10
     steps:
       - uses: actions/checkout@v3
-
-      # - uses: aquaproj/aqua-installer@v1.1.2
-      #   with:
-      #     aqua_version: v1.20.2
-      #     enable_aqua_install: true
-      #     aqua_opts: ""
-      #     working_directory: "${{ github.workspace }}"
-      - name: aqua-install
-        run: |
-          curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v1.1.2/aqua-installer | bash -s -- -i /usr/local/bin/aqua
-          # echo "$HOME/.local/share/aquaproj-aqua/bin" >> $GITHUB_PATH
-          # [[ -e "${AQUA_CONFIG}" ]] && echo "✅ AQUA_CONFIG: ${AQUA_CONFIG} exists" ||  echo "::error ❗ unable to validate the target file: ${AQUA_CONFIG} exists"
-          ls -lla "${{ github.workspace }}"
+      - uses: aquaproj/aqua-installer@v1.1.2
+        with:
+          aqua_version: v1.20.2
+          enable_aqua_install: true
+          # aqua_opts: ""
         env:
-          AQUA_CONFIG: '${{ github.workspace }}/aqua.yaml'
+          # AQUA_CONFIG: '${{ github.workspace }}/aqua.yaml'
           AQUA_LOG_LEVEL: debug
           AQUA_OPTS: ""
+            # working_directory: "${{ github.workspace }}"
+
+      # - name: aqua-install
+      #   run: |
+      #     curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v1.1.2/aqua-installer | bash -s -- -i /usr/local/bin/aqua
+      #     # echo "$HOME/.local/share/aquaproj-aqua/bin" >> $GITHUB_PATH
+      #     # [[ -e "${AQUA_CONFIG}" ]] && echo "✅ AQUA_CONFIG: ${AQUA_CONFIG} exists" ||  echo "::error ❗ unable to validate the target file: ${AQUA_CONFIG} exists"
+      #     ls -lla "${{ github.workspace }}"
+      #   env:
+      #     AQUA_CONFIG: '${{ github.workspace }}/aqua.yaml'
+      #     AQUA_LOG_LEVEL: debug
+      #     AQUA_OPTS: ""
       - name: env-config-go
         run: |
           echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
